version: "3.4"

services:
    wordpress:
        build: .
        image: ifrs/ps:latest
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DEBUG: "true"
        volumes:
            - .:/var/www/html/wp-content/themes/ifrs-ps-theme
    mysql:
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
