version: "3.6"

services:
    wordpress:
        image: wordpress:4-php7.2-apache
        networks:
            - default
            - proxy
        volumes:
            - wp_data:/var/www/html
            - ./:/var/www/html/wp-content/themes/ifrs-ps-theme
        depends_on:
            - mysql
        environment:
            VIRTUAL_HOST: "${VIRTUAL_HOST}"
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
            WORDPRESS_AUTH_KEY: "${WORDPRESS_AUTH_KEY}"
            WORDPRESS_SECURE_AUTH_KEY: "${WORDPRESS_SECURE_AUTH_KEY}"
            WORDPRESS_LOGGED_IN_KEY: "${WORDPRESS_LOGGED_IN_KEY}"
            WORDPRESS_NONCE_KEY: "${WORDPRESS_NONCE_KEY}"
            WORDPRESS_AUTH_SALT: "${WORDPRESS_AUTH_SALT}"
            WORDPRESS_SECURE_AUTH_SALT: "${WORDPRESS_SECURE_AUTH_SALT}"
            WORDPRESS_LOGGED_IN_SALT: "${WORDPRESS_LOGGED_IN_SALT}"
            WORDPRESS_NONCE_SALT: "${WORDPRESS_NONCE_SALT}"
            WORDPRESS_DEBUG: "true"
    wp-cli:
        image: wordpress:cli
        volumes:
            - wp_data:/var/www/html
        depends_on:
            - wordpress
            - mysql
        tty: true
    mysql:
        image: mysql:5
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - default
            - proxy
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            VIRTUAL_HOST: "phpmyadmin.${VIRTUAL_HOST}"
volumes:
    db_data:
    wp_data:
networks:
    default:
    proxy:
        external:
            name: ${REVERSE_PROXY_NETWORK}
