version: "3.4"

services:
    wordpress:
        image: ifrs/ps:latest
        restart: on-failure=5
        volumes:
            - uploads:/var/www/html/wp-content/uploads
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
            WORDPRESS_AUTH_KEY: "${WORDPRESS_AUTH_KEY}"
            WORDPRESS_SECURE_AUTH_KEY: "${WORDPRESS_SECURE_AUTH_KEY}"
            WORDPRESS_LOGGED_IN_KEY: "${WORDPRESS_LOGGED_IN_KEY}"
            WORDPRESS_NONCE_KEY: "${WORDPRESS_NONCE_KEY}"
            WORDPRESS_AUTH_SALT: "${WORDPRESS_AUTH_SALT}"
            WORDPRESS_SECURE_AUTH_SALT: "${WORDPRESS_SECURE_AUTH_SALT}"
            WORDPRESS_LOGGED_IN_SALT: "${WORDPRESS_LOGGED_IN_SALT}"
            WORDPRESS_NONCE_SALT: "${WORDPRESS_NONCE_SALT}"
            WORDPRESS_DEBUG: "false"
    mysql:
        image: mysql:5
        restart: on-failure=5
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
volumes:
    db_data:
    uploads:
