version: "3.4"

services:
    wordpress:
        image: wordpress:4-php7.2-apache
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        volumes:
            - content:/var/www/html/wp-content
            - ./:/var/www/html/wp-content/themes/ifrs-ps-theme
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
            WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
            WORDPRESS_AUTH_KEY: "${WORDPRESS_AUTH_KEY}"
            WORDPRESS_SECURE_AUTH_KEY: "${WORDPRESS_SECURE_AUTH_KEY}"
            WORDPRESS_LOGGED_IN_KEY: "${WORDPRESS_LOGGED_IN_KEY}"
            WORDPRESS_NONCE_KEY: "${WORDPRESS_NONCE_KEY}"
            WORDPRESS_AUTH_SALT: "${WORDPRESS_AUTH_SALT}"
            WORDPRESS_SECURE_AUTH_SALT: "${WORDPRESS_SECURE_AUTH_SALT}"
            WORDPRESS_LOGGED_IN_SALT: "${WORDPRESS_LOGGED_IN_SALT}"
            WORDPRESS_NONCE_SALT: "${WORDPRESS_NONCE_SALT}"
            WORDPRESS_DEBUG: "true"
    mysql:
        image: mysql:5
        restart: on-failure
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
volumes:
    db_data:
    content:
